apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: mkck3x303-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: mkck3x303-nodejs 
  name: mkck3x303-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: mkck3x303-nodejs 
